m2l_pages_home:
    path:    /
    defaults:
        _controller: M2LPagesBundle:Main:index
    requirements:
        page: \d*
        
m2l_pages_admin:
    path:    /admin
    defaults:
        _controller: M2LPagesBundle:Admin:admin
    requirements:
        page: \d+
        
m2l_message_admin:
    path:    /admin/message
    defaults:
        _controller: M2LPagesBundle:Admin:message
    requirements:
        _methods: GET

m2l_pages_tresorier:
    path:    /tresorier
    defaults:
        _controller: M2LPagesBundle:Admin:tresorier
    requirements:
        page: \d+
        
m2l_list_user:
    path:    /tresorier/list
    defaults:
        _controller: M2LPagesBundle:Admin:list
    requirements:
        _methods: GET
        
m2l_pages_frais:
    path:    /frais
    defaults:
        _controller: M2LPagesBundle:Main:frais
    requirements:
        page: \d*
        
m2l_pages_frais_add:
    path:    /add_frais
    defaults:
        _controller: M2LPagesBundle:Main:addfrais
    requirements:
        page: \d*
        
m2l_pages_frais_edit:
    path:    /edit_frais/{id}
    defaults:
        _controller: M2LPagesBundle:Main:editfrais
    requirements:
        id: \d+
        
m2l_pages_frais_delete:
    path:    /delete_frais/{id}
    defaults:
        _controller: M2LPagesBundle:Main:deletefrais
    requirements:
        id: \d+
        
m2l_pages_frais_validate:
    path:    /validate_frais/{id}
    defaults:
        _controller: M2LPagesBundle:Main:validatefrais
    requirements:
        id: \d+
        
m2l_pages_adherent:
    path:    /adherent
    defaults:
        _controller: M2LPagesBundle:Main:adherent
    requirements:
        page: \d*
        
m2l_pages_adherent_add:
    path:    /add_adherent
    defaults:
        _controller: M2LPagesBundle:Main:addadherent
    requirements:
        page: \d*
        
m2l_pages_adherent_edit:
    path:    /edit_adherent/{id}
    defaults:
        _controller: M2LPagesBundle:Main:editadherent
    requirements:
        id: \d+
        
m2l_pages_adherent_delete:
    path:    /delete_adherent/{id}
    defaults:
        _controller: M2LPagesBundle:Main:deleteadherent
    requirements:
        id: \d+
        
m2l_pages_contact:
    path:    /contact
    defaults:
        _controller: M2LPagesBundle:Main:contact
    requirements:
        page: \d+
        
m2l_pages_contact_success:
    path:    /contact_success
    defaults:
        _controller: M2LPagesBundle:Main:contactsuccess
    requirements:
        page: \d+