m2l_pages_home:
    path:    /
    defaults:
        _controller: M2LPagesBundle:Main:index
    requirements:
        page: \d*
        
m2l_pages_view:
    path:    /view
    defaults:
        _controller: M2LPagesBundle:Main:view
    requirements:
        page: \d*
        
m2l_list_frais:
    path:    /view/listfrais
    defaults:
        _controller: M2LPagesBundle:Main:listfrais
    requirements:
        _methods: GET
        
m2l_pages_frais:
    path:    /frais
    defaults:
        _controller: M2LPagesBundle:Main:frais
    requirements:
        page: \d*
        
m2l_pages_frais_edit:
    path:    /frais/edit
    defaults:
        _controller: M2LPagesBundle:Main:editfrais
        
m2l_pages_frais_delete:
    path:    /frais/delete
    defaults:
        _controller: M2LPagesBundle:Main:deletefrais
        
m2l_pages_contact:
    path:    /contact
    defaults:
        _controller: M2LPagesBundle:Main:contact
    requirements:
        page: \d+
        
m2l_pages_tresorier:
    path:    /tresorier
    defaults:
        _controller: M2LPagesBundle:Admin:tresorier
    requirements:
        page: \d+
        
m2l_list_user:
    path:    /tresorier/list
    defaults:
        _controller: M2LPagesBundle:Admin:list
    requirements:
        _methods: GET