m2l_pages_home:
    path:    /
    defaults:
        _controller: M2LPagesBundle:Main:index
    requirements:
        page: \d*
        
m2l_pages_contact:
    path:    /contact
    defaults:
        _controller: M2LPagesBundle:Main:contact
    requirements:
        page: \d+