m2l_pages_home:
    path:    /
    defaults:
        _controller: M2LPagesBundle:Main:index
    requirements:
        page: \d*
        
m2l_pages_frais:
    path:    /frais
    defaults:
        _controller: M2LPagesBundle:Main:frais
    requirements:
        page: \d*
        
m2l_pages_contact:
    path:    /contact
    defaults:
        _controller: M2LPagesBundle:Main:contact
    requirements:
        page: \d+
        
m2l_pages_tresorier:
    path:    /tresorier
    defaults:
        _controller: M2LPagesBundle:Admin:tresorier
    requirements:
        page: \d+
        
m2l_list_user:
    path:    /tresorier/list
    defaults:
        _controller: M2LPagesBundle:Admin:list
    requirements:
        _methods: GET