m2l_pages:
    resource: "@M2LPagesBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@M2LUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@M2LUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@M2LUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@M2LUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@M2LUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


