m2l_api:
    resource: "@M2LApiBundle/Resources/config/routing.yml"
    prefix:   /

m2l_pages:
    resource: "@M2LPagesBundle/Resources/config/routing.yml"
    prefix:   /
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    
fos_user_security:
    resource: "@M2LUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@M2LUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@M2LUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@M2LUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@M2LUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


