
security:
    encoders:
        M2L\UserBundle\Entity\User: Sha512
        
    role_hierarchy:
        ROLE_ADMIN:    [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|img|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:    fos_user_security_logout
                target:    /
            remember_me:
                secret: %secret%
                
    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
