
security:
    encoders:
        M2L\UserBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_ADHERENT:    [ROLE_DEFAULT]
        ROLE_REPRESENTANT:    [ROLE_ADHERENT]
        ROLE_TRESORIER:    [ROLE_ADHERENT]
        ROLE_ADMIN: [ROLE_TRESORIER, ROLE_REPRESENTANT, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false
        api:
            pattern: ^/
            fos_oauth: true
            stateless: false
            anonymous: true
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                remember_me: true
            logout:
                path:    fos_user_security_logout
                target:    /
            remember_me:
                secret: %secret%
                lifetime: 31536000
                always_remember_me: true
            switch_user: { role: ROLE_ADMIN }
        dev:
            pattern: ^/(_(profiler|wdt)|css|img|js)/
            security: false
    access_control:
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
