# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    m2l.form.registration:
        class: M2L\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: m2l_user_registration }
