<?php

namespace M2L\PagesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdherentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdherentRepository extends EntityRepository
{
}
